### PR TITLE
upgraded dependencies, moved dev dependency to dev deps, test against latest node version

### PR DESCRIPTION
**Pull request by dsp1589**
as title

### CODE REVIEW

**Comment by dsp1589** [comment]
> Problem with main menu. Check the screen
> Screenshot from 2020-04-07 09-15-43

Fixed
https://github.com/Cezerin2/cezerin2-admin/pull/55/commits/721bad21b6a69a46dc7d25e61eb0c37a54a8fd54

**Comment by dsp1589** [comment]
https://github.com/Cezerin2/cezerin2-admin/pull/55/commits/721bad21b6a69a46dc7d25e61eb0c37a54a8fd54

fix for css style break updated

**Comment by vamcart** [comment]
> [721bad2](https://github.com/Cezerin2/cezerin2-admin/commit/721bad21b6a69a46dc7d25e61eb0c37a54a8fd54)
> 
> fix for css style break updated

Menu is fine now.
By i have a product while editing, edding categories, products

**Comment by dsp1589** [comment]
Issue resolved. check now! Upload images button functionality not working. In old code as well new updated deps code. need a revisit to make changes based on new deps

**Comment by vamcart** [comment]
Thanks.
But category edit not working.
And i can't approve PR with not working upload for images.

How to use this?! How to add images by users?!

> Issue resolved. check now! Upload images button functionality not working. In old code as well new updated deps code. need a revisit to make changes based on new deps

**Comment by vamcart** [comment]
Same problem with image upload in Admin - Settings - General - Logo

http://localhost:3002/settings/general/logo - blank page

Ans problem with uplpad slider at:
Admin - Settings - Theme - http://localhost:3002/settings/theme
Blank page.

Lookls like all the code with image uploads needs to be fixed.

**Pull request merged**
