### PR TITLE
[Products] Fix product image in list

### PR DESCRIPTION
**Pull request by Bogdan-p**
Fixes one of the issues from: https://github.com/Cezerin2/cezerin2-admin/issues/17
_- Cannot display image after uploading_

### CODE REVIEW

**Comment by vamcart** [comment]
Nothing changed for me with this PR.

Product Images displayed ony after page reloading in the browser.

**Comment by LuBuss** [comment]
That will not fix the issue

**Comment by vamcart** [comment]
Sorry, it's work for me too.

Need to change cezerin2 service like this - https://github.com/Cezerin2/cezerin2/pull/120

And images works fine.

**Comment by Bogdan-p** [comment]
Yes @vamcart, I fixed that issue locally a while before, because i couldn't delete product images. I didn't realize this issue was connected to that one. Great job on fixing that bug also!

**Comment by vamcart** [comment]
Thanks. You make cezerin2 a little better

**Pull request merged**
